version: '3'
services:
  mongodb:
    image: mongo 
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE= db
    ports:
      - "27017:27017"
    volumes:
      - mymongo-data:/data/db
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: jugnu670
      POSTGRES_DB: jugnu
      POSTGRES_USER: jugnu
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"
  web :
    depends_on: 
      - mongodb
      - postgres
      - redis
    links:
      - mongodb:mongodb
      - postgres:postgres
      - redis:redis
    build : .
    restart: always
    ports :
      - "80:80"
volumes:
  postgres_data:
  mymongo-data: